#' Fit parametric models to growth data
#' 
#' \code{fit_growth_parametric} uses \code{\link{gcFitModel}} from the
#' \pkg{grofit} package to fit a parametric model to growth data. Several
#' candidate models are fitted, and the model with the best AIC is returned.
#'
#' @param df A data frame
#' @param time Name of the column in \code{df} that contains time data
#' @param data Name of the column in \code{df} that contains growth data
#' @param ... Additional arguments for \code{\link{gcFitModel}}
#'
#' @return A list of types \code{gcfit} and \code{gcFitModel}
#'     \item{raw.time}{Raw data given to the function; equivalent to \code{time}}
#'     \item{raw.data}{Raw data given to the function; equivalent to \code{data}}
#'     \item{gcID}{Vector (of any length) identifying the growth curve data}
#'     \item{fit.time}{Vector of fitted concentration values}
#'     \item{fit.data}{Vector of fitted growth values}
#'     \item{parameters}{List of estimated growth values}
#'     \item{A}{Maximum growth value}
#'     \item{mu}{Maximum slope}
#'     \item{lambda}{Lag phase}
#'     \item{integral}{Integral under growth curve}
#'     \item{model}{String naming the parametric model used}
#'     \item{nls}{\code{nls} object generated by the R internal function \code{\link{nls}}}
#'     \item{reliable}{Logical, indicating wether the provided data is reliable (to be set manually)}
#'     \item{fitFlag}{Logical, indicating wether a model could be successfully fitted to data}
#'     \item{control}{Object of class \code{grofit.control} containing list of options passed to the function as \code{control}}
#'     \item{fit_type}{The type of fit, here 'model'}
#' @seealso For specific parametric models, see \code{\link{fit_growth_logistic}}, \code{\link{fit_growth_richards}}, \code{\link{fit_growth_gompertz}}, \code{\link{fit_growth_gompertz.exp}}
#' @seealso \code{\link{gcFitModel}}
#' @importFrom lazyeval lazy
#' @export
#'
#' @examples
#' \dontrun{
#' # Fit the data given in columns Time and OD600
#' fit_growth_parametric(df=mydata, Time, OD600)}
#'
fit_growth_parametric <- function(df, time, data, ...)
{
    fit_growth_parametric_(df, time_col=lazy(time), data_col=lazy(data), ...)
}


#' @export
#' @param time_col String giving the name of the column in \code{df} that
#' contains time data
#' @param data_col String giving the name of the column in \code{df} that
#' contains growth data
#' @importFrom grofit gcFitModel
#' @importFrom lazyeval lazy_eval
#' @rdname fit_growth_parametric
#' @examples
#' \dontrun{
#' # Fit the data given in columns Time and OD600
#' fit_growth_parametric_(df=mydata, time_col='Time', data_col='OD600')}
#'
fit_growth_parametric_ <- function(df, time_col, data_col, ...)
{
    result <- list()

    result$type <- 'parametric'
    
    result$uses_grofit <- TRUE
    result$grofit <- gcFitModel(time=lazy_eval(time_col, df), 
                                data=lazy_eval(data_col, df), ...)
    
    result$lag_length <- result$grofit$parameters$lambda
    result$max_rate <- result$grofit$parameters$mu
    result$max_growth <- result$grofit$parameters$A
    result$integral <- result$grofit$parameters$integral
    
    result$residuals <- result$grofit$raw.data - result$grofit$fit.data
    
    result$raw$df <- df
    result$raw$time_col <- as.character(time_col)[1]
    result$raw$data_col <- as.character(data_col)[1]
    
    class(result) <- c('gcfit')
    result
}
