#' Fit smooth splines to growth data
#' 
#' \code{fit_growth_spline} uses \code{\link{gcFitSpline}} from the \pkg{grofit}
#' package to fit a smoothed spline to growth data.
#'
#' @param df A data frame
#' @param time Name of the column in \code{df} that contains time data
#' @param growth Name of the column in \code{df} that contains growth data
#' @param ... Additional arguments for \code{\link{gcFitSpline}}
#'
#' @return A list of types \code{gcfit} and \code{gcFitSpline}
#'     \item{raw.time}{Raw data given to the function; equivalent to \code{time}}
#'     \item{raw.data}{Raw data given to the function; equivalent to \code{data}}
#'     \item{gcID}{Vector (of any length) identifying the growth curve data}
#'     \item{fit.time}{Vector of fitted concentration values}
#'     \item{fit.data}{Vector of fitted growth values}
#'     \item{parameters}{List of estimated growth values from spline fit: \code{A}, maximum growth value;
#' \code{mu}, maximum slope; \code{lambda}, lag-phase, \code{integral},
#' integral under growth curve}
#'     \item{parametersLowess}{List of estimated growth values from \code{\link{lowess}} fit: \code{A}, maximum growth value; \code{mu}, maximum slope; \code{lambda}, lag-phase}
#'     \item{spline}{\code{smooth.spline} object generated by \code{\link{smooth.spline}}}
#'     \item{reliable}{Logical, indicating wether the provided data is reliable (to be set manually)}
#'     \item{fitFlag}{Logical, indicating wether a spline could be successfully fitted to data}
#'     \item{control}{Object of class \code{grofit.control} containing list of options passed to the function as \code{control}}
#'     \item{fit_type}{The type of fit, here 'spline'}
#' @seealso \code{\link{gcFitSpline}}
#' @importFrom lazyeval lazy
#' @export
#'
#' @examples
#' \dontrun{
#' # Fit the data given in columns Time and OD600
#' fit_growth_spline(df=mydata, Time, OD600)}
#'
fit_growth_spline <- function(df, time, growth, ...)
{
    fit_growth_spline_(df, time_col=lazy(time), growth_col=lazy(growth), ...)
}


#' @param time_col String giving the name of the column in \code{df} that
#' contains time data
#' @param growth_col String giving the name of the column in \code{df} that
#' contains growth data
#' @export
#' @importFrom grofit gcFitSpline
#' @importFrom lazyeval lazy_eval
#' @rdname fit_growth_spline
#' @examples
#' \dontrun{
#' # Fit the data given in columns Time and OD600
#' fit_growth_spline_(df=mydata, time_col='Time', growth_col='OD600')}
#'
fit_growth_spline_ <- function(df, time_col, growth_col, ...)
{
    sfit <- gcFitSpline(time=lazy_eval(time_col, df), 
                        data=lazy_eval(growth_col, df), ...)
    sfit$fit_type <- 'spline'
    class(sfit) <- c('gcfit', 'gcFitSpline')
    sfit
}
